/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as PublicDecksRouteImport } from './routes/public-decks'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlayPublicRouteImport } from './routes/play-public'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicDeckIdRouteImport } from './routes/public.$deckId'
import { Route as PlayDeckIdRouteImport } from './routes/play.$deckId'
import { Route as EditDeckIdRouteImport } from './routes/edit.$deckId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDecksRoute = PublicDecksRouteImport.update({
  id: '/public-decks',
  path: '/public-decks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPublicRoute = PlayPublicRouteImport.update({
  id: '/play-public',
  path: '/play-public',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDeckIdRoute = PublicDeckIdRouteImport.update({
  id: '/public/$deckId',
  path: '/public/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDeckIdRoute = PlayDeckIdRouteImport.update({
  id: '/play/$deckId',
  path: '/play/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditDeckIdRoute = EditDeckIdRouteImport.update({
  id: '/edit/$deckId',
  path: '/edit/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/create': typeof CreateRoute
  '/decks': typeof DecksRoute
  '/play-public': typeof PlayPublicRoute
  '/progress': typeof ProgressRoute
  '/public-decks': typeof PublicDecksRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/edit/$deckId': typeof EditDeckIdRoute
  '/play/$deckId': typeof PlayDeckIdRoute
  '/public/$deckId': typeof PublicDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/create': typeof CreateRoute
  '/decks': typeof DecksRoute
  '/play-public': typeof PlayPublicRoute
  '/progress': typeof ProgressRoute
  '/public-decks': typeof PublicDecksRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/edit/$deckId': typeof EditDeckIdRoute
  '/play/$deckId': typeof PlayDeckIdRoute
  '/public/$deckId': typeof PublicDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/create': typeof CreateRoute
  '/decks': typeof DecksRoute
  '/play-public': typeof PlayPublicRoute
  '/progress': typeof ProgressRoute
  '/public-decks': typeof PublicDecksRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/edit/$deckId': typeof EditDeckIdRoute
  '/play/$deckId': typeof PlayDeckIdRoute
  '/public/$deckId': typeof PublicDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/create'
    | '/decks'
    | '/play-public'
    | '/progress'
    | '/public-decks'
    | '/scores'
    | '/settings'
    | '/edit/$deckId'
    | '/play/$deckId'
    | '/public/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/create'
    | '/decks'
    | '/play-public'
    | '/progress'
    | '/public-decks'
    | '/scores'
    | '/settings'
    | '/edit/$deckId'
    | '/play/$deckId'
    | '/public/$deckId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/create'
    | '/decks'
    | '/play-public'
    | '/progress'
    | '/public-decks'
    | '/scores'
    | '/settings'
    | '/edit/$deckId'
    | '/play/$deckId'
    | '/public/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CreateRoute: typeof CreateRoute
  DecksRoute: typeof DecksRoute
  PlayPublicRoute: typeof PlayPublicRoute
  ProgressRoute: typeof ProgressRoute
  PublicDecksRoute: typeof PublicDecksRoute
  ScoresRoute: typeof ScoresRoute
  SettingsRoute: typeof SettingsRoute
  EditDeckIdRoute: typeof EditDeckIdRoute
  PlayDeckIdRoute: typeof PlayDeckIdRoute
  PublicDeckIdRoute: typeof PublicDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-decks': {
      id: '/public-decks'
      path: '/public-decks'
      fullPath: '/public-decks'
      preLoaderRoute: typeof PublicDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-public': {
      id: '/play-public'
      path: '/play-public'
      fullPath: '/play-public'
      preLoaderRoute: typeof PlayPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$deckId': {
      id: '/public/$deckId'
      path: '/public/$deckId'
      fullPath: '/public/$deckId'
      preLoaderRoute: typeof PublicDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$deckId': {
      id: '/play/$deckId'
      path: '/play/$deckId'
      fullPath: '/play/$deckId'
      preLoaderRoute: typeof PlayDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$deckId': {
      id: '/edit/$deckId'
      path: '/edit/$deckId'
      fullPath: '/edit/$deckId'
      preLoaderRoute: typeof EditDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CreateRoute: CreateRoute,
  DecksRoute: DecksRoute,
  PlayPublicRoute: PlayPublicRoute,
  ProgressRoute: ProgressRoute,
  PublicDecksRoute: PublicDecksRoute,
  ScoresRoute: ScoresRoute,
  SettingsRoute: SettingsRoute,
  EditDeckIdRoute: EditDeckIdRoute,
  PlayDeckIdRoute: PlayDeckIdRoute,
  PublicDeckIdRoute: PublicDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
